title: Yujing Wu # your name (or website title) here
logo: "/images/profile pic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Graduate student studying Urban Spatial Analytics at the University of Pennsylvania
  <br><br>
  <a href="https://www.linkedin.com/in/yujing-wu-04150498/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
